### ISSUE TITLE
Crash on `exists` check

### ISSUE THREAD

**Issue by ItzNotABug** [ItzNotABug/DocumentFileCompat#10]
> Hello @ItzNotABug,  
> Thanks for this optimization, which makes my life so much easier!
> However I reproduce the problem when the file associated with the uri has been deleted. The original lib returns a DocumentFile on which I can perform an exists() which returns false, the DocumentFileCompat crashes with the error message java.lang.IllegalArgumentException: Failed to determine if primary:Pictures/xxxxxxxxxxxx is child of primary:Pictures/xxxxxxxxx java.io.FileNotFoundException: Missing file for primary:Pictures/xxxxxxxxxx  
> 
> Do you have an idea for fixing the lib aside catch the exception in my app? Thanks a lot!

_Originally posted by @provalinf in https://github.com/ItzNotABug/DocumentFileCompat/issues/6#issuecomment-2478427668_

**Comment by ItzNotABug** [comment]
@provalinf I've created a separate issue for better tracking.

**Comment by ItzNotABug** [comment]
@provalinf This fix is now available on maven central. Update to `1.0.9`.

**Comment by provalinf** [comment]
@ItzNotABug Thx but same problem, crash is (also?) before exist() on fromSingleUri() call
![image](https://github.com/user-attachments/assets/bdc8b9bc-16a7-4001-8de7-ee92188e90ce)

Of course, I'll return null, but the best practice would be to have the object to call exist() on.

**Comment by ItzNotABug** [comment]
> @ItzNotABug Thx but same problem, crash is (also?) before exist() on fromSingleUri() call

I'll take a look at it again! Can you share a full stacktrace though?

**Comment by provalinf** [comment]
![image](https://github.com/user-attachments/assets/7aa9682e-00e8-4376-8954-547c1356ed0c)
![image](https://github.com/user-attachments/assets/b219fc97-257c-441b-93ff-25ca71a279d8)
```
FATAL EXCEPTION: main
                 Process: com.yyyy.xxxx.android.debug, PID: 8424
                 java.lang.IllegalArgumentException: Failed to determine if primary:Pictures/xxxx/24-11-14_10-47-40-741_13241_3981_resi_20241114104744.jpg is child of primary:Pictures/xxxx: java.io.FileNotFoundException: Missing file for primary:Pictures/xxxx/24-11-14_10-47-40-741_13241_3981_resi_20241114104744.jpg at /storage/emulated/0/Pictures/xxxx/24-11-14_10-47-40-741_13241_3981_resi_20241114104744.jpg
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
                 	at android.content.ContentResolver.query(ContentResolver.java:1229)
                 	at android.content.ContentResolver.query(ContentResolver.java:1161)
                 	at android.content.ContentResolver.query(ContentResolver.java:1117)
                 	at com.lazygeniouz.dfc.resolver.ResolverCompat.getCursor(ResolverCompat.kt:139)
                 	at com.lazygeniouz.dfc.file.internals.SingleDocumentFileCompat$Companion.make$dfc_release(SingleDocumentFileCompat.kt:99)
                 	at com.lazygeniouz.dfc.file.DocumentFileCompat$Companion.fromSingleUri(DocumentFileCompat.kt:222)
                 	at com.lazygeniouz.dfc.file.DocumentFileCompat.fromSingleUri(Unknown Source:2)
                 	at com.yyyy.xxxx.android.utils.FileCompatUtil.fromSingleUri(FileCompatUtil.java:25)
                 	at com.yyyy.xxxx.android.data.modelDTO.questionnaire.response.GalleryAnswerDTO.localFileExists(GalleryAnswerDTO.java:244)
                 	at com.yyyy.xxxx.android.view.fragment.GalleryActivityFragment.showImage(GalleryActivityFragment.java:170)
                 	at com.yyyy.xxxx.android.view.fragment.GalleryActivityFragment.lambda$onCreateView$2$com-yyyy-xxxx-android-view-fragment-GalleryActivityFragment(GalleryActivityFragment.java:87)
                 	at com.yyyy.xxxx.android.view.fragment.GalleryActivityFragment$$ExternalSyntheticLambda3.onItemClick(D8$$SyntheticClass:0)
                 	at com.yyyy.xxxx.android.view.adapter.GalleryAdapter.lambda$getView$0$com-yyyy-xxxx-android-view-adapter-GalleryAdapter(GalleryAdapter.java:151)
                 	at com.yyyy.xxxx.android.view.adapter.GalleryAdapter$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
                 	at android.view.View.performClick(View.java:7659)
                 	at android.view.View.performClickInternal(View.java:7636)
                 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                 	at android.view.View$PerformClick.run(View.java:30156)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by ItzNotABug** [comment]
@provalinf Thanks for the stacktrace.
What I see here is that the error could be mitigated here, I'll try to reproduce this issue locally and see what can we do.

**Comment by provalinf** [comment]
Ok, normally just like this you should be able to reproduce it :
```
DocumentFileCompat folderDir = getFileImageFolder();
DocumentFileCompat destinationFile = folderDir.findFile("image.jpg");
Uri fileUri = destinationFile.getUri();
// Wait delete image
DocumentFileCompat.fromSingleUri(context, fileUri);
// Crash

**Comment by ItzNotABug** [comment]
I see the issue now -
1. `DocumentFile` just stores the **Context** and the **Uri** on init.
2. Meanwhile `DocumentFileCompat` reaches to the `ContentResolver` on init and crashes when the file doesn't exist.

I'll shoot a PR for this. Thanks for all the details 🙌

**Comment by ItzNotABug** [comment]
I've merged the fix and released a new version to Maven Central (`1.1`).
Please note that availability on Maven Central can sometimes be delayed.

**Comment by provalinf** [comment]
Ok it's functional, even if it doesn't return an object to call exists() on, it returns null so that's the expected result, thanks for your responsiveness!

I see you've left the error even though it no longer crashes, I don't know if it's deliberate.
![image](https://github.com/user-attachments/assets/15e2d193-1f9d-4449-8ad0-85b0fb7a9abf)

**Comment by ItzNotABug** [comment]
> I see you've left the error even though it no longer crashes, I don't know if it's deliberate.

Yes, the error is deliberately logged to make sure that any unrelated issue can be easily identified and debugged. However, it can be safely ignored in this context.

If you face any other bugs, feel free to create a new issue with details. Closing this one!
