### ISSUE TITLE
Error when using fromSingleUri

### ISSUE THREAD

**Issue by Anthonyy232** [ItzNotABug/DocumentFileCompat#6]
Error from logcat is: 
`FATAL EXCEPTION: main
                                                                                                    Process: com.name.app, PID: 22818
                                                                                                    java.lang.IllegalArgumentException: Failed to determine if primary:Pictures/Wallpaper/38qs4xw3x5k71_result.jpg is child of primary:Pictures/Wallpaper: java.io.FileNotFoundException: Missing file for primary:Pictures/Wallpaper at /storage/emulated/0/Pictures/Wallpaper
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                                                                                                    	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1226)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1158)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1114)
                                                                                                    	at com.lazygeniouz.dfc.resolver.ResolverCompat.getCursor(ResolverCompat.kt:133)
                                                                                                    	at com.lazygeniouz.dfc.file.internals.SingleDocumentFileCompat$Companion.make$dfc_release(SingleDocumentFileCompat.kt:99)
                                                                                                    	at com.lazygeniouz.dfc.file.DocumentFileCompat$Companion.fromSingleUri(DocumentFileCompat.kt:222)
                                                                                                    	at com.name.app.feature.ViewModel$updateImages$1.invokeSuspend(AppViewModel.kt:56)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b0e134b, Dispatchers.Main.immediate]
`

The code that yields the error is:
`if (viewModel.coverUri != null) {
                    val coverFile = DocumentFileCompat.fromSingleUri(context, viewModel.coverUri.toUri())
                    if (coverFile == null || !coverFile.exists()) {
                        repository.updateImage(null))
                    }
                }`
Other sections of my code also yield the same error and what's responsible seems to be fromSingleUri and methods that it uses. I couldn't figure out what was wrong with it specifically. Maybe you'll have some insight into this.

The same code works with DocumentFile (the original). I can confirm that the content URI is not the problem because I have other libraries as well as official ones that work with it perfectly.

**Comment by Anthonyy232** [comment]
Any update? Still occurring as of latest update

**Comment by ItzNotABug** [comment]
Hey @Anthonyy232 👋,
Haven't had the time to look at this, apologies for that.

I'll probably take a look into this around this week, thanks for the reminder!

**Comment by Anthonyy232** [comment]
Sure! I'm actually going to open another issue, although it's a much less important one

**Comment by ItzNotABug** [comment]
Hey @Anthonyy232,
I checked this issue you posted with the stacktrace.

I could not reproduce this via the sample app, which uses `DocumentFileCompat.fromSingleUri` [here](https://github.com/ItzNotABug/DocumentFileCompat/blob/69e83caf5705f94413ad0eb1e13e6e242d9f1f67/app/src/main/java/com/lazygeniouz/filecompat/example/performance/FilesPerformance.kt#L41).

Could you share more details, or maybe a sample demo app that can reproduce this issue?

**Comment by Anthonyy232** [comment]
Yes, actually, I've been trying to reproduce this one but haven't encountered it again yet. I'll try to switch over and see if it happens again, otherwise it was probably an error on my part, and I'll close out the issue.

**Comment by ItzNotABug** [comment]
@Anthonyy232 can this issue be closed?

**Comment by Anthonyy232** [comment]
Yes! I will let you know otherwise, but so far has been stable. Must have been an issue on my end.

**Comment by provalinf** [comment]
Hello @ItzNotABug,  
Thanks for this optimization, which makes my life so much easier!
However I reproduce the problem when the file associated with the uri has been deleted. The original lib returns a DocumentFile on which I can perform an exists() which returns false, the DocumentFileCompat crashes with the error message java.lang.IllegalArgumentException: Failed to determine if primary:Pictures/xxxxxxxxxxxx is child of primary:Pictures/xxxxxxxxx java.io.FileNotFoundException: Missing file for primary:Pictures/xxxxxxxxxx  

Do you have an idea for fixing the lib aside catch the exception in my app? Thanks a lot!
