### ISSUE TITLE
Crash when using DocumentFileCompat with the Downloads folder

### ISSUE THREAD

**Issue by Anthonyy232** [ItzNotABug/DocumentFileCompat#8]
Occurred on virtual device Pixel 5 API 26
Getting crash error when trying to access the device's Download folder. It works on folders that I created (and probably other system folders too). Seems to stem from DocumentFileCompat.fromTreeUri. It works for me in the same exact place when using regular DocumentFile instead of DocumentFileCompat.

My code (the non-working version):
```kotlin
return DocumentFileCompat.fromTreeUri(context, folderUri.toUri())?.name
``` 
Bypassed the crash using try/catch and switching to DocumentFile when DocumentFileCompat doesn't work, but yeah, seems like a bug so fyi.

<details><summary>Error Code</summary>
<p>

java.lang.NullPointerException: cursor.getString(1) must not be null
                                                                                                    	at com.lazygeniouz.dfc.file.internals.TreeDocumentFileCompat$Companion.make$dfc_release(TreeDocumentFileCompat.kt:128)
                                                                                                    	at com.lazygeniouz.dfc.file.DocumentFileCompat$Companion.fromTreeUri(DocumentFileCompat.kt:211)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.wallpaper_service.WallpaperService2$refreshAlbum$1.invokeSuspend(WallpaperService2.kt:637)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

</p>
</details>

**Comment by ItzNotABug** [comment]
I tried this as well, couldn't reproduce.
Matter of fact, I tested the changes on your `Paperize` app repo.

Here's how I tested -
1. Reduced wallpaper change to 1 min for faster checks
2. Removed the `try/catch`s, used only `DocumentFileCompat` APIs & added certain logs
3. Added a few images in the Downloads folder of the above mentioned virtual device
4. Added Album in Paperize, Selected both Home & Lock screen for wallpaper change
5. No crashes, logs properly displayed Folder name, file names (wallpapers), etc.

**Comment by Anthonyy232** [comment]
Can I ask where you removed the try/catch from? I just tested it on my app, and I was able to reproduce it (will push latest code to my repository if you want to test on the same version I am). It's getting a little late over here, but I can do a short demo video tomorrow. If you aren't able to reproduce it with this, I suspect that it might have to do with the images that I am using (maybe metadata?). I'll upload the [images]() (sorry about the type of images, it's just what I had on hand to test. Will remove after a bit so it isn't a case of self-promotion) I'm using to test in case, but I'm not entirely sure and I will do some testing with other images tomrrow. 

This is how I modified my code to reproduce the error on Pixel 5 API 26:
```kotlin
fun getWallpaperFromFolder(folderUri: String, context: Context): List<String> {
    /*try {
        val folderDocumentFile = DocumentFileCompat.fromTreeUri(context, folderUri.toUri())
        return listFilesRecursive(folderDocumentFile, context)
    } catch (e: Exception) {
        val folderDocumentFile = DocumentFile.fromTreeUri(context, folderUri.toUri())
        return listFilesRecursive(folderDocumentFile, context)
    }*/
    val folderDocumentFile = DocumentFileCompat.fromTreeUri(context, folderUri.toUri())
    return listFilesRecursive(folderDocumentFile, context)
}
``` 

This is the error log that I get:
<details><summary>Details</summary>
<p>

```kotlin
2024-06-11 01:41:14.019 23351-23423 AndroidRuntime          pid-23351                            E  FATAL EXCEPTION: DefaultDispatcher-worker-8 (Ask Gemini)
                                                                                                    Process: com.anthonyla.paperize, PID: 23351
                                                                                                    java.lang.NullPointerException: cursor.getString(1) must not be null
                                                                                                    	at com.lazygeniouz.dfc.file.internals.TreeDocumentFileCompat$Companion.make$dfc_release(TreeDocumentFileCompat.kt:128)
                                                                                                    	at com.lazygeniouz.dfc.file.DocumentFileCompat$Companion.fromTreeUri(DocumentFileCompat.kt:211)
                                                                                                    	at com.anthonyla.paperize.core.WallpaperUtilKt.getWallpaperFromFolder(WallpaperUtil.kt:160)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.presentation.album.AlbumsViewModel$updateAlbums$1.invokeSuspend(AlbumsViewModel.kt:114)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
2024-06-11 01:43:53.055 24204-24204 AndroidRuntime          com.anthonyla.paperize               E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.anthonyla.paperize, PID: 24204
                                                                                                    java.lang.NullPointerException: cursor.getString(1) must not be null
                                                                                                    	at com.lazygeniouz.dfc.file.internals.TreeDocumentFileCompat$Companion.make$dfc_release(TreeDocumentFileCompat.kt:128)
                                                                                                    	at com.lazygeniouz.dfc.file.DocumentFileCompat$Companion.fromTreeUri(DocumentFileCompat.kt:211)
                                                                                                    	at com.anthonyla.paperize.core.WallpaperUtilKt.getWallpaperFromFolder(WallpaperUtil.kt:160)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.presentation.add_album_screen.AddAlbumViewModel$onEvent$6.invokeSuspend(AddAlbumViewModel.kt:142)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.presentation.add_album_screen.AddAlbumViewModel.onEvent(AddAlbumViewModel.kt:140)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.presentation.add_album_screen.AddAlbumScreenKt$AddAlbumScreen$folderPickerLauncher$1$1.invoke(AddAlbumScreen.kt:91)
                                                                                                    	at com.anthonyla.paperize.feature.wallpaper.presentation.add_album_screen.AddAlbumScreenKt$AddAlbumScreen$folderPickerLauncher$1$1.invoke(AddAlbumScreen.kt:85)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.invoke$lambda$0(ActivityResultRegistry.kt:106)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.$r8$lambda$VLs2Oqd6MzDD-LGilzyhNhDSH_4(Unknown Source:0)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1$$ExternalSyntheticLambda0.onActivityResult(D8$$SyntheticClass:0)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:7235)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
                                                                                                    	at android.app.ActivityThread.-wrap19(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

``` 

</p>
</details> 

I will look more into it tomorrow, thanks for the help

**Comment by ItzNotABug** [comment]
Hey @Anthonyy232,
I tested by removing all `try/catch` usage project wide and only using `DocumentFileCompat` apis.

Additionally, I don't think it could be due to the images. But I'll try again against your latest master branch with the provided images.

**Comment by ItzNotABug** [comment]
I cloned the master branch, ran it, again not reproducible.
Changes to test -

```kotlin
fun getWallpaperFromFolder(folderUri: String, context: Context): List<String> {
    val folderDocumentFile = DocumentFileCompat.fromTreeUri(context, folderUri.toUri())
    return listFilesRecursive(folderDocumentFile, context).also {
        Log.d("Paperize", it.toString())
    }
}
```

and 

```kotlin
fun getFolderNameFromUri(folderUri: String, context: Context): String? {
   return DocumentFileCompat.fromTreeUri(context, folderUri.toUri())?.name.also {
        Log.d("Paperize", it.toString())
    }
}
```

Output - 

<img width="1287" alt="Screenshot 2024-06-11 at 6 44 07 PM" src="https://github.com/ItzNotABug/DocumentFileCompat/assets/20625965/3a66766c-3935-4ed8-8f08-52909c42029d">

---
Here's a screen-record as well -


https://github.com/ItzNotABug/DocumentFileCompat/assets/20625965/d02a3d84-ab06-46cf-9306-4510858ec6b3

**Comment by Anthonyy232** [comment]
Huh, interesting. I suppose with all that if you can't reproduce it then it might be an issue on my end, I will see if I can figure out why.

Here's a recording 

https://github.com/ItzNotABug/DocumentFileCompat/assets/60626873/b44cbfdc-959b-4bbd-b026-1f8b69a381e4

**Comment by ItzNotABug** [comment]
Pretty weird actually.
I tested with the sample app as well and couldn't reproduce the error. Any other ideas or reproduction steps?

**Comment by Anthonyy232** [comment]
Not at the moment unfortuantely. Will also be gone for the next 3+ weeks so I won't be able to look into it. But I will update if I find anything. Let me know if you want me to close this, or you can close it yourself I believe.

**Comment by ItzNotABug** [comment]
No worries, I'll keep this open for now.
